### PR TITLE
Update italian HISTORY and README

### PR DESCRIPTION
**Pull request by bovirus**
@katahiromz 

Please check and merge, Thanks.

What does this string means in detail

"Relaxed font selection requirements."

in relation to "Relaxed"?

### CODE REVIEW

**Comment by katahiromz** [comment]
`Relaxed` means Loosed.

**Comment by bovirus** [comment]
@katahiromz 

Could you procise better the meaing of this function?

"Less requirement for font selection"?

**Comment by katahiromz** [comment]
> "Less requirement for font selection"?

Yes.

**Comment by katahiromz** [comment]
OK?

**Comment by bovirus** [comment]
Yes. thanks.

**Pull request merged**
